# Generated by Django 2.2 on 2019-06-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipper',
            name='email',
            field=models.CharField(default=50, max_length=255),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='first_name',
            field=models.CharField(default=50, max_length=255),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='last_name',
            field=models.CharField(default=50, max_length=255),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='password',
            field=models.CharField(default=25, max_length=255),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='phone_number',
            field=models.CharField(default=50, max_length=255),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='username',
            field=models.CharField(default=25, max_length=255),
        ),
    ]
