# Generated by Django 2.2 on 2019-06-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190610_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='total_order',
            new_name='total_ship',
        ),
        migrations.AddField(
            model_name='order',
            name='total_order',
            field=models.IntegerField(default=0),
        ),
    ]
